package it.gestrap.entita;
// Generated 23 giu 2020, 22:40:43 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Clienti generated by hbm2java
 */
@Entity
@Table(name = "clienti", catalog = "gestionerapportini", uniqueConstraints = @UniqueConstraint(columnNames = "codice"))
public class Clienti implements java.io.Serializable {

	private Integer id;
	private String codice;
	private String nome;
	private String descrizione;
	private String piva;
	private Set<Commesse> commesses = new HashSet<Commesse>(0);

	public Clienti() {
	}

	public Clienti(String codice, String nome) {
		this.codice = codice;
		this.nome = nome;
	}

	public Clienti(String codice, String nome, String descrizione, String piva, Set<Commesse> commesses) {
		this.codice = codice;
		this.nome = nome;
		this.descrizione = descrizione;
		this.piva = piva;
		this.commesses = commesses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "codice", unique = true, nullable = false, length = 6)
	public String getCodice() {
		return this.codice;
	}

	public void setCodice(String codice) {
		this.codice = codice;
	}

	@Column(name = "nome", nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "descrizione", length = 45)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "piva", length = 11)
	public String getPiva() {
		return this.piva;
	}

	public void setPiva(String piva) {
		this.piva = piva;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clienti")
	public Set<Commesse> getCommesses() {
		return this.commesses;
	}

	public void setCommesses(Set<Commesse> commesses) {
		this.commesses = commesses;
	}

	@Override
	public String toString() {
		return "Clienti [id=" + id + ", codice=" + codice + ", nome=" + nome + ", descrizione=" + descrizione
				+ ", piva=" + piva + ", commesses=" + commesses + "]";
	}
	
	

}
