package it.gestrap.entita;
// Generated 30 giu 2020, 16:48:26 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comdip generated by hbm2java
 */
@Entity
@Table(name = "comdip", catalog = "gestionerapportini")
public class Comdip implements java.io.Serializable {

	private Integer id;
	private Commesse commesse;
	private Dipendenti dipendenti;
	private Date datainizio;
	private Date datafine;

	public Comdip() {
	}

	public Comdip(Commesse commesse, Dipendenti dipendenti, Date datainizio) {
		this.commesse = commesse;
		this.dipendenti = dipendenti;
		this.datainizio = datainizio;
	}

	public Comdip(Commesse commesse, Dipendenti dipendenti, Date datainizio, Date datafine) {
		this.commesse = commesse;
		this.dipendenti = dipendenti;
		this.datainizio = datainizio;
		this.datafine = datafine;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcomm", nullable = false)
	public Commesse getCommesse() {
		return this.commesse;
	}

	public void setCommesse(Commesse commesse) {
		this.commesse = commesse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddip", nullable = false)
	public Dipendenti getDipendenti() {
		return this.dipendenti;
	}

	public void setDipendenti(Dipendenti dipendenti) {
		this.dipendenti = dipendenti;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datainizio", nullable = false, length = 10)
	public Date getDatainizio() {
		return this.datainizio;
	}

	public void setDatainizio(Date datainizio) {
		this.datainizio = datainizio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datafine", length = 10)
	public Date getDatafine() {
		return this.datafine;
	}

	public void setDatafine(Date datafine) {
		this.datafine = datafine;
	}

}
