package it.gestrap.entita;
// Generated 30 giu 2020, 16:48:26 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Dipendenti generated by hbm2java
 */
@Entity
@Table(name = "dipendenti", catalog = "gestionerapportini", uniqueConstraints = {
		@UniqueConstraint(columnNames = "matricola"),
		@UniqueConstraint(columnNames = { "matricola", "nome", "cognome", "codfiscale" }) })
public class Dipendenti implements java.io.Serializable {

	private Integer id;
	private Profilo profilo;
	private Ruoli ruoli;
	private TipoContratto tipocontratto;
	private String matricola;
	private String nome;
	private String cognome;
	private Date datanascita;
	private String codfiscale;
	private String password;
	private String residenza;
	private String numerotelefono;
	private int stipendioannuo;
	private Date dataassunzione;
	private Date datalicenziamento;
	private Set<Comdip> comdips = new HashSet<Comdip>(0);
	private Set<Rapportini> rapportinis = new HashSet<Rapportini>(0);

	public Dipendenti() {
	}

	public Dipendenti(Profilo profilo, Ruoli ruoli, TipoContratto tipocontratto, String matricola, String nome,
			String cognome, Date datanascita, String codfiscale, String password, String numerotelefono,
			int stipendioannuo, Date dataassunzione) {
		this.profilo = profilo;
		this.ruoli = ruoli;
		this.tipocontratto = tipocontratto;
		this.matricola = matricola;
		this.nome = nome;
		this.cognome = cognome;
		this.datanascita = datanascita;
		this.codfiscale = codfiscale;
		this.password = password;
		this.numerotelefono = numerotelefono;
		this.stipendioannuo = stipendioannuo;
		this.dataassunzione = dataassunzione;
	}

	public Dipendenti(Profilo profilo, Ruoli ruoli, TipoContratto tipocontratto, String matricola, String nome,
			String cognome, Date datanascita, String codfiscale, String password, String residenza,
			String numerotelefono, int stipendioannuo, Date dataassunzione, Date datalicenziamento, Set<Comdip> comdips,
			Set<Rapportini> rapportinis) {
		this.profilo = profilo;
		this.ruoli = ruoli;
		this.tipocontratto = tipocontratto;
		this.matricola = matricola;
		this.nome = nome;
		this.cognome = cognome;
		this.datanascita = datanascita;
		this.codfiscale = codfiscale;
		this.password = password;
		this.residenza = residenza;
		this.numerotelefono = numerotelefono;
		this.stipendioannuo = stipendioannuo;
		this.dataassunzione = dataassunzione;
		this.datalicenziamento = datalicenziamento;
		this.comdips = comdips;
		this.rapportinis = rapportinis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idprofilo", nullable = false)
	public Profilo getProfilo() {
		return this.profilo;
	}

	public void setProfilo(Profilo profilo) {
		this.profilo = profilo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idruoli", nullable = false)
	public Ruoli getRuoli() {
		return this.ruoli;
	}

	public void setRuoli(Ruoli ruoli) {
		this.ruoli = ruoli;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idtipcontratto", nullable = false)
	public TipoContratto getTipocontratto() {
		return this.tipocontratto;
	}

	public void setTipocontratto(TipoContratto tipocontratto) {
		this.tipocontratto = tipocontratto;
	}

	@Column(name = "matricola", unique = true, nullable = false, length = 10)
	public String getMatricola() {
		return this.matricola;
	}

	public void setMatricola(String matricola) {
		this.matricola = matricola;
	}

	@Column(name = "nome", nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "cognome", nullable = false, length = 45)
	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datanascita", nullable = false, length = 10)
	public Date getDatanascita() {
		return this.datanascita;
	}

	public void setDatanascita(Date datanascita) {
		this.datanascita = datanascita;
	}

	@Column(name = "codfiscale", nullable = false, length = 16)
	public String getCodfiscale() {
		return this.codfiscale;
	}

	public void setCodfiscale(String codfiscale) {
		this.codfiscale = codfiscale;
	}

	@Column(name = "password", nullable = false, length = 12)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "residenza", length = 2)
	public String getResidenza() {
		return this.residenza;
	}

	public void setResidenza(String residenza) {
		this.residenza = residenza;
	}

	@Column(name = "numerotelefono", nullable = false, length = 10)
	public String getNumerotelefono() {
		return this.numerotelefono;
	}

	public void setNumerotelefono(String numerotelefono) {
		this.numerotelefono = numerotelefono;
	}

	@Column(name = "stipendioannuo", nullable = false)
	public int getStipendioannuo() {
		return this.stipendioannuo;
	}

	public void setStipendioannuo(int stipendioannuo) {
		this.stipendioannuo = stipendioannuo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataassunzione", nullable = false, length = 10)
	public Date getDataassunzione() {
		return this.dataassunzione;
	}

	public void setDataassunzione(Date dataassunzione) {
		this.dataassunzione = dataassunzione;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datalicenziamento", length = 10)
	public Date getDatalicenziamento() {
		return this.datalicenziamento;
	}

	public void setDatalicenziamento(Date datalicenziamento) {
		this.datalicenziamento = datalicenziamento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dipendenti")
	public Set<Comdip> getComdips() {
		return this.comdips;
	}

	public void setComdips(Set<Comdip> comdips) {
		this.comdips = comdips;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dipendenti")
	public Set<Rapportini> getRapportinis() {
		return this.rapportinis;
	}

	public void setRapportinis(Set<Rapportini> rapportinis) {
		this.rapportinis = rapportinis;
	}

}
