package it.gestrap.entita;
// Generated 26 giu 2020, 11:16:25 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Profilo generated by hbm2java
 */
@Entity
@Table(name = "profilo", catalog = "gestionerapportini", uniqueConstraints = @UniqueConstraint(columnNames = "iddipen"))
public class Profilo implements java.io.Serializable {

	private Integer id;
	private Dipendenti dipendenti;
	private String profilo;

	public Profilo() {
	}

	public Profilo(Dipendenti dipendenti, String profilo) {
		this.dipendenti = dipendenti;
		this.profilo = profilo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddipen", unique = true, nullable = false)
	public Dipendenti getDipendenti() {
		return this.dipendenti;
	}

	public void setDipendenti(Dipendenti dipendenti) {
		this.dipendenti = dipendenti;
	}

	@Column(name = "profilo", nullable = false, length = 20)
	public String getProfilo() {
		return this.profilo;
	}

	public void setProfilo(String profilo) {
		this.profilo = profilo;
	}

}
