package it.gestrap.entita;
// Generated 23 giu 2020, 22:40:43 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Rapportini generated by hbm2java
 */
@Entity
@Table(name = "rapportini", catalog = "gestionerapportini", uniqueConstraints = @UniqueConstraint(columnNames = {
		"data", "orelavorate", "iddipendenti" }))
public class Rapportini implements java.io.Serializable {

	private Integer id;
	private Commesse commesse;
	private Dipendenti dipendenti;
	private Date data;
	private int orelavorate;

	public Rapportini() {
	}

	public Rapportini(Commesse commesse, Dipendenti dipendenti, Date data, int orelavorate) {
		this.commesse = commesse;
		this.dipendenti = dipendenti;
		this.data = data;
		this.orelavorate = orelavorate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcommesse", nullable = false)
	public Commesse getCommesse() {
		return this.commesse;
	}

	public void setCommesse(Commesse commesse) {
		this.commesse = commesse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddipendenti", nullable = false)
	public Dipendenti getDipendenti() {
		return this.dipendenti;
	}

	public void setDipendenti(Dipendenti dipendenti) {
		this.dipendenti = dipendenti;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data", nullable = false, length = 10)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@Column(name = "orelavorate", nullable = false)
	public int getOrelavorate() {
		return this.orelavorate;
	}

	public void setOrelavorate(int orelavorate) {
		this.orelavorate = orelavorate;
	}

}
